Write a function to compute 5/0 and use try/except to catch the exceptions.
def zerodiv():
    return 5/0
try:
    zerodiv()
except ZeroDivisionError:
    print ("division by zero!")
finally:
    print ('In finally block ')
